import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from './Layout.module.css'
import utilStyles from '../styles/Utils.module.css'

export const siteTitle = "Grafbase Demo Site"

export default function Layout({ children, home }) {
    return (
        <div>
            <Head>
                <meta name="og:title" content={siteTitle} />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta property="og:image" content={"https://grafbase.com/api/og?title=" + siteTitle}></meta>
                <link rel="icon" href="/favicon.png" />
            </Head>
            <header className={styles.header}>
                <div className={utilStyles.description}>                    
                    <div>
                        <Link
                        href="https://grafbase.com"
                        target="_blank"
                        rel="noopener noreferrer"
                        >
                            By{' '}
                            <Image
                                src="/logo.svg"
                                alt="Grafbase Logo"
                                className={utilStyles.grafbaseLogo}
                                width={100}
                                height={24}
                                priority
                            />
                        </Link>
                    </div>
                </div>
                {
                    !home && (
                        <div className={styles.backToHome}>
                            <Link href="/">← Back to home</Link>
                        </div>
                    )
                }
            </header>
            <main className={styles.main}>{children}</main>
        </div>
    )
}